# Generated by Django 2.0.4 on 2018-04-29 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 29, 15, 7, 51, 139412)),
        ),
    ]
