# Generated by Django 2.0.4 on 2018-04-29 09:51

import datetime
from django.db import migrations, models
import magnum_online.functions


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180429_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('R', 'Rejected'), ('C', 'Canceled'), ('S', 'Completed')], default='I', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qr_hash',
            field=models.CharField(default=magnum_online.functions.randhash6, max_length=6, unique=True),
        ),
    ]
