# Generated by Django 2.0.4 on 2018-04-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180429_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Completed'), ('R', 'Rejected'), ('I', 'Incomplete'), ('C', 'Canceled')], default='I', max_length=3),
        ),
    ]
