# Generated by Django 2.0.4 on 2018-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180429_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('C', 'Canceled'), ('S', 'Completed'), ('R', 'Rejected'), ('I', 'Incomplete')], default='I', max_length=3),
        ),
    ]
