# Generated by Django 2.0.4 on 2018-05-31 07:41

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180531_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='full_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_full_image),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('C', 'Canceled'), ('R', 'Rejected'), ('S', 'Completed'), ('I', 'Incomplete')], default='I', max_length=3),
        ),
    ]
