# Generated by Django 2.0.4 on 2018-05-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180531_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('I', 'Incomplete'), ('C', 'Canceled'), ('S', 'Completed'), ('R', 'Rejected')], default='I', max_length=3),
        ),
    ]
