# Generated by Django 2.0.4 on 2018-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180531_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('S', 'Completed'), ('C', 'Canceled'), ('R', 'Rejected'), ('I', 'Incomplete')], default='I', max_length=3),
        ),
    ]
