# Generated by Django 2.0.4 on 2018-05-31 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180531_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('full_image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_full_image)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('main_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('C', 'Canceled'), ('S', 'Completed'), ('I', 'Incomplete')], default='I', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Manufacturer'),
        ),
    ]
